# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://git.speiyou.cn/app/xes_bclib_ios_privatepods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'XESLoggerDemo’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'CocoaLumberjack/Default', '~> 3.0.0'
end
